const sillybladees = [
    {
        title:"Bindle",
        imgdesc:"SillySmurf",
        type:"item",
        country:"Cambodia",
        dabloons:"cheap",
        kieranrating:"badrate",
        img:"https://www.shutterstock.com/image-vector/bindle-stick-runaway-hobo-mascot-600nw-2363704785.jpg",
    },
    {
        title:"Three Gorges Dam",
        imgdesc:"BigDam",
        type:"structure",
        country:"China",
        dabloons:"expensive",
        kieranrating:"badrate",
        img:"https://img2.chinadaily.com.cn/images/202304/30/644de0a8a310b60580cc2408.png",
    },
    {
        title:"Great Ball",
        imgdesc:"Ball",
        type:"item",
        country:"Japan",
        dabloons:"cheap",
        kieranrating:"goodrate",
        img:"https://www.pokemoncenter.com/images/DAMRoot/High/10000/P8737_710-95847_02.jpg",
    },
    {
        title:"The Tower",
        imgdesc:"leaning tower of pisa",
        type:"structure",
        country:"Italy",
        dabloons:"expensive",
        kieranrating:"badrate",
        img:"https://cdn.britannica.com/88/80588-050-8D944BFE/Leaning-Tower-of-Pisa-Italy.jpg",
    },
    {
        title:"Bamboo Scaffolding",
        imgdesc:"Hong Kong Bamboo Scaffolding",
        type:"structure",
        country:"Hong Kong",
        dabloons:"cheap",
        kieranrating:"goodrate",
        img:"https://multimedia.scmp.com/infographics/culture/article/3183200/bamboo-scaffolding/img/building2.jpg",
    },
    {
        title:"Thai Racing Boat",
        imgdesc:"Fast Boat",
        type:"item",
        country:"Thailand",
        dabloons:"cheap",
        kieranrating:"goodrate",
        img:"https://www.mudmotorkit.com/wp-content/uploads/2019/05/thai-racing-1-SPS-Swamp-Runner.jpg",
    },
    {
        title:"The honda",
        imgdesc:"big truck",
        type:"item",
        country:"Japan",
        dabloons:"cheap",
        kieranrating:"goodrate",
        img:"https://bringatrailer.com/wp-content/uploads/2016/12/Screen-Shot-2016-12-06-at-12.20.17-PM.png?fit=940%2C711",
    },
    {
        title:"Perfection",
        imgdesc:"911 turbo",
        type:"item",
        country:"Germany",
        dabloons:"expensive",
        kieranrating:"goodrate",
        img:"https://assets.bwbx.io/images/users/iqjWHBFdfxIU/ijsxlvQB.bu8/v0/1200x800.jpg",
    },
    {
        title:"432 Park Avenue",
        imgdesc:"ugly midtown building",
        type:"structure",
        country:"USA",
        dabloons:"expensive",
        kieranrating:"badrate",
        img:"https://upload.wikimedia.org/wikipedia/commons/1/10/432_Park_Avenue%2C_NY_%28cropped%292.jpg",
    },
]
export { sillybladees };
//cardarray